apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: howk
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/component: test
    app.kubernetes.io/part-of: howk
spec:
  selector:
    app.kubernetes.io/name: echo-server
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: howk
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/component: test
    app.kubernetes.io/part-of: howk
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
        app.kubernetes.io/component: test
        app.kubernetes.io/part-of: howk
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo:31
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: HTTP_PORT
              value: "8080"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
