apiVersion: batch/v1
kind: Job
metadata:
  name: stress-test
  namespace: howk
  labels:
    app.kubernetes.io/name: stress-test
    app.kubernetes.io/component: test
    app.kubernetes.io/part-of: howk
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress-test
        app.kubernetes.io/component: test
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until wget -q -O - http://api:8080/health 2>/dev/null; do
                echo "Waiting for API..."
                sleep 2
              done
              echo "API is ready!"
              sleep 5  # Give API a moment to be fully ready
        - name: wait-for-echo
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until wget -q -O - http://echo-server:8080/ 2>/dev/null; do
                echo "Waiting for echo server..."
                sleep 1
              done
              echo "Echo server is ready!"
      containers:
        - name: stress-test
          image: howk-stress-test:latest
          imagePullPolicy: IfNotPresent
          command:
            - stress-test
            - -api=http://api:8080
            - -config=stress-test
            - -endpoint=http://echo-server:8080/webhook
            - -workers=10
            - -rate=20
            - -duration=2m
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
  backoffLimit: 0
