apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: howk
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: howk
spec:
  selector:
    app.kubernetes.io/name: redpanda
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
    - port: 9644
      targetPort: 9644
      name: admin
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: howk
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: howk
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/component: messaging
        app.kubernetes.io/part-of: howk
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v25.3.6
          command:
            - /bin/sh
            - -c
            - |
              rpk redpanda start \
                --kafka-addr 0.0.0.0:9092 \
                --advertise-kafka-addr redpanda:9092 \
                --rpc-addr 0.0.0.0:33145 \
                --advertise-rpc-addr redpanda:33145 \
                --smp 1 \
                --memory 1G \
                --mode dev-container \
                --default-log-level warn
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: admin
            - containerPort: 33145
              name: rpc
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            exec:
              command:
                - rpk
                - cluster
                - health
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - rpk
                - cluster
                - health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: redpanda-data
              mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
    - metadata:
        name: redpanda-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
