apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: howk
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: howk
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: howk
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: howk
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: howk
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "Waiting for Redis..."
                sleep 1
              done
              echo "Redis is ready!"
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z redpanda 9092; do
                echo "Waiting for Kafka..."
                sleep 1
              done
              echo "Kafka is ready!"
      containers:
        - name: api
          image: howk:api-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: HOWK_CONFIG
              value: /config/config.yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: howk-config
