apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: howk
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: howk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/part-of: howk
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "Waiting for Redis..."
                sleep 1
              done
              echo "Redis is ready!"
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until nc -z redpanda 9092; do
                echo "Waiting for Kafka..."
                sleep 1
              done
              echo "Kafka is ready!"
      containers:
        - name: scheduler
          image: howk:scheduler-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HOWK_CONFIG
              value: /config/config.yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ps aux | grep -v grep | grep howk-scheduler"
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: howk-config
